"de_nuke_old"

{

	"name"		"de_nuke_old"
	"imagename"	"map-nuke-overall"

	"t_arms"	"models/weapons/t_arms_balkan.mdl"
	"ct_arms"	"models/weapons/ct_arms_gsg9.mdl"
	"t_models"
	{
		"tm_balkan_variantA"	""
		"tm_balkan_variantB"	""
		"tm_balkan_variantC"	""
		"tm_balkan_variantD"	""
		"tm_balkan_variantE"	""
	}
	"ct_models"
	{
		"ctm_gsg9"""
		"ctm_gsg9_variantA"""
		"ctm_gsg9_variantB"""
		"ctm_gsg9_variantC"""
		"ctm_gsg9_variantD"""
	}
}